export const baseConfig = {
  GROUPED_COMPLEMENTARY_INFORMATION_INACTIVE_TIME_RATE:
    "Tiempo promedio inactivo:",
  NO_INFORMATION: "Sin información",
  EQUIVALENT_ELECTIVE: "Equivalente: ",
  EMPLOYED_TRUE: "Empleado",
  EMPLOYED_FALSE: "Cesante",
  EDUCATIONAL_SYSTEM_TRUE: "Si",
  EDUCATIONAL_SYSTEM_FALSE: "No",
  COMPLEMENTARY_INFORMATION_EMPLOYED_TOOLTIP: "Informacion del indicador 0",
  COMPLEMENTARY_INFORMATION_TYPE_ADMISSION_TOOLTIP:
    "Información del indicador 1",
  COMPLEMENTARY_INFORMATION_EMPLOYED_EDUCATIONAL_SYSTEM_TOOLTIP:
    "Información del indicador 2",
  COMPLEMENTARY_INFORMATION_EMPLOYED_INSTITUTION_TOOLTIP:
    "Información del indicador 3",
  COMPLEMENTARY_INFORMATION_EMPLOYED_MONTHS_TOOLTIP:
    "Información del indicador 4",

  GROUPED_COMPLEMENTARY_INFORMATION_TOTAL_STUDENTS_TOOLTIP: "IA1",
  GROUPED_COMPLEMENTARY_INFORMATION_TIMELY_UNIVERSITY_DEGREE_RATE_TOOLTIP:
    "IA2",
  GROUPED_COMPLEMENTARY_INFORMATION_UNIVERSITY_DEGREE_RATE_TOOLTIP: "IA3",
  GROUPED_COMPLEMENTARY_INFORMATION_AVERAGE_TIME_UNIVERSITY_DEGREE_TOOLTIP:
    "IA4",

  GROUPED_COMPLEMENTARY_INFORMATION_EMPLEABILITY_RATE_TOOLTIP: "IA5",
  GROUPED_COMPLEMENTARY_INFORMATION_EMPLEABILITY_AVERAGE_TIME_FINDING_JOB_TOOLTIP:
    "IA6",
  GROUPED_COMPLEMENTARY_INFORMATION_EMPLEABILITY_RATE_EDUCATIONAL_SYSTEM_TOOLTIP:
    "IA7",
  GROUPED_COMPLEMENTARY_INFORMATION_INACTIVE_TIME_RATE_TOOLTIP: "IA 8",
  GROUPED_COMPLEMENTARY_INFORMATION_RETENTION_RATE_TOOLTIP: "IA9",

  ACTIVE_EXTERNAL_EVALUATION_BOX_COLOR: "#718096",
  INACTIVE_EXTERNAL_EVALUATION_BOX_COLOR: "#F8690C",
  EXTERNAL_EVALUATION_BOX_ALL_TRANSITION_DURATION: "all 0.5s",
  EXTERNAL_EVALUATION_BOX_BACKGROUND_COLOR: "rgb(245,245,245)",
  EXTERNAL_EVALUATION_BOX_BORDER_WIDTH_ACTIVE: "2px",
  EXTERNAL_EVALUATION_BOX_BORDER_WIDTH_INACTIVE: "3px",
  EXTERNAL_EVALUATION_BOX_TEXT_COLOR: "black",
  FLOW_EXTERNAL_EVALUATION_BOX_COLOR: "#F56565",
  EXPLICIT_SEMESTER_EXTERNAL_EVALUATION_BOX_COLOR: "#ECC94B",
  REQUISITE_EXTERNAL_EVALUATION_BOX_COLOR: "#4299E1",
  STATE_COURSE_DEFAULT_COLOR_EXTERNAL_EVALUATION: "rgb(253,158,44)",
  STATE_COURSE_DEFAULT_DARK_COLOR_EXTERNAL_EVALUATION: "#181A1B",
  STATE_COURSE_DEFAULT_LIGHT_COLOR_EXTERNAL_EVALUATION: "rgb(245,245,245)",

  GRAPHIC_ADVANCE: "Gráfico Avance",
  COURSE_PLAN: "Malla",
  ACTIVE_COURSE_BOX_COLOR: "#718096",
  CANCELED_HISTORIC_TOOLTIP_LABEL: "Anulada",
  CHECK_STUDENT_FROM_LIST_LABEL: "Ver estudiante",
  COURSE_BOX_ALL_TRANSITION_DURATION: "all 0.5s",
  COURSE_BOX_BACKGROUND_COLOR: "rgb(245,245,245)",
  COURSE_BOX_BORDER_WIDTH_ACTIVE: "2px",
  COURSE_BOX_BORDER_WIDTH_INACTIVE: "1px",
  COURSE_BOX_TEXT_COLOR: "black",
  CREDITS_LABEL: "Créditos",
  CUMULATED_GRADE_COLOR: "rgb(173,66,244)",
  CUMULATED_GRADE_LABEL: "PGA",
  CURRICULUM_LABEL: "Plan",
  ADMISSION_TYPE_LABEL: "Tipo de admisión",
  COHORT_LABEL: "Cohorte",
  DASHBOARD_SEMESTERS_LIST_MOBILE_BREAKPOINT: 1200,
  DROPOUT_BACKGROUND_COLOR: "rgb(252,249,165)",
  DROPOUT_PREDICTION: "Percentil de riesgo",
  DROPOUT_PREDICTION_ACCURACY_ENABLED: false,
  DROPOUT_PREDICTION_ACCURACY: "modelo:",
  DROPOUT_PREDICTION_DESCRIPTION:
    "El sistema estima un percentil de riesgo de abandono",
  DROPOUT_TEXT_COLOR: "black",

  COMPLEMENTARY_INFORMATION_BACKGROUND_COLOR: "rgb(165,206,252)",
  COMPLEMENTARY_INFORMATION_EMPLOYED_INFORMATION: "Datos de empleabilidad",
  COMPLEMENTARY_INFORMATION_EMPLOYED_EDUCATIONAL_SYSTEM: "Sistema educacional:",
  COMPLEMENTARY_INFORMATION: "Información Complementaria",

  GROUPED_COMPLEMENTARY_INFORMATION: "Información Complementaria Agrupada",
  COMPLEMENTARY_INFORMATION_EMPLOYED: "Estado ocupacional:",
  COMPLEMENTARY_INFORMATION_MONTHS_TEXT: "meses",
  COMPLEMENTARY_INFORMATION_SEMESTER_TEXT: "semestres",
  COMPLEMENTARY_INFORMATION_TYPE_ADMISSION: "Tipo de ingreso: ",

  GROUPED_COMPLEMENTARY_INFORMATION_TOTAL_STUDENTS: "Cantidad de estudiantes:",
  GROUPED_COMPLEMENTARY_INFORMATION_UNIVERSITY_DEGREE_RATE:
    "Tasa de titulación:",
  GROUPED_COMPLEMENTARY_INFORMATION_RETENTION_RATE: "Tasa de retención:",
  GROUPED_COMPLEMENTARY_INFORMATION_TIMELY_UNIVERSITY_DEGREE_RATE:
    "Tasa de titulación oportuna:",
  GROUPED_COMPLEMENTARY_INFORMATION_AVERAGE_TIME_UNIVERSITY_DEGREE:
    "Tiempo promedio de titulación:",
  GROUPED_COMPLEMENTARY_INFORMATION_EMPLEABILITY_RATE: "Tasa de ocupación:",
  GROUPED_COMPLEMENTARY_INFORMATION_EMPLEABILITY_AVERAGE_TIME_FINDING_JOB:
    "Tiempo promedio en encontrar empleo:",
  GROUPED_COMPLEMENTARY_INFORMATION_EMPLEABILITY_RATE_EDUCATIONAL_SYSTEM:
    "Tasa de ocupación en sistema educativo:",

  GROUPED_OFF: "No agrupado ",
  GROUPED_ON: "Agrupado ",
  GROUPED_REPORT_INFORMATION: "Informe Información Agrupada",
  COMPLEMENTARY_INFORMATION_PERCENT_MARK: "%",
  COMPLEMENTARY_INFORMATION_INITIAL_EVALUATION:
    "Evaluación inicial diagnóstica: ",
  COMPLEMENTARY_INFORMATION_FINAL_EVALUATION:
    "Evaluación nacional diagnóstica: ",
  COMPLEMENTARY_INFORMATION_EMPLOYED_INSTITUTION: "Nombre de institución:",
  COMPLEMENTARY_INFORMATION_EMPLOYED_MONTHS: "Meses hasta encontrar trabajo:",
  COMPLEMENTARY_INFORMATION_TEXT_COLOR: "black",
  DOWNLOAD_WORD: "Descargar Informe",
  DOWNLOAD_WORD_STUDENT_COMPLEMENTARY_INFO_TEXT:
    "La siguiente imagen muestra información complementaria asociada al ingreso del estudiante",
  DOWNLOAD_WORD_STUDENT_PROGRESS_TEXT:
    "La siguiente gráfica evidencia el progreso del estudiante en el respectivo ciclo formativo. El valor en color azul corresponde a la cantidad de asignaturas aprobadas, en tanto que el valor porcentual evidencia el avance del estudiante en cada ciclo formativo. ",
  DOWNLOAD_WORD_STUDENT_TREND_TEXT:
    "El siguiente gráfico muestra la tendencia en el avance del estudiante. En color azul se aprecia su Promedio Semestral Ponderado, mientras que en color morado se señala su Promedio General Acumulado. Finalmente, en tono gris se encuentra el Promedio General Acumulado de la carrera.",
  DOWNLOAD_WORD_STUDENT_PLAN_TEXT:
    "La siguiente imagen corresponde a la malla curricular. La siguiente imagen muestra indicadores correspondientes a los y las estudiantes de la carrera de acuerdo a los parámetros seleccionados en cuanto a Plan de estudios, Tipo de Admisión (PSU-Ingreso PACE – Ingreso Especial) y Cohorte de ingreso.",

  DOWNLOAD_WORD_GROUPED_COMPLEMENTARY_INFO_TEXT:
    "La siguiente imagen muestra indicadores correspondientes a los y las estudiantes de la carrera de acuerdo a los parámetros seleccionados en cuanto a Plan de estudios, Tipo de Admisión (PSU-Ingreso PACE – Ingreso Especial) y Cohorte de ingreso. Si todos los datos están disponibles se podrán ver los siguientes indicadores: ",
  DOWNLOAD_WORD_GROUPED_COMPLEMENTARY_INFO_SECOND_TEXT:
    "En el caso particular de su búsqueda, los indicadores son los siguientes:",
  DOWNLOAD_WORD_GROUPED_TREND_TEXT:
    "El siguiente gráfico evidencia en un tono morado el Promedio General Acumulado de la cohorte filtrada, la cual se visualiza de manera comparativa con el Promedio General Acumulado del Plan curricular seleccionado, el cual se encuentra en tono gris. ",
  DOWNLOAD_WORD_GROUPED_TREND_SECOND_TEXT:
    "El valor numérico señalado en la parte superior de cada 1er y 2do semestre corresponde a la cantidad de estudiantes que inscribieron alguna asignatura en el semestre especificado y permite analizar la deserción estudiantil en el tiempo.",
  DOWNLOAD_WORD_GROUPED_PLAN_TEXT:
    "La siguiente imagen corresponde a la malla curricular del plan de estudios seleccionado",
  DOWNLOAD_WORD_GROUPED_PLAN_SECOND_TEXT:
    "En el caso particular de su búsqueda el progreso en la malla curricular es el siguiente:",
  DOWNLOAD_WORD_GROUPED_PLAN_TEXT_01:
    "En un tono morado más oscuro se encuentran las asignaturas en las que un 75% o más de los estudiantes han aprobado el curso.",
  DOWNLOAD_WORD_GROUPED_PLAN_TEXT_02:
    "En un tono morado un poco más claro, se aprecian aquellas asignaturas en las que el 74% a 50% de los estudiantes ha aprobado.",
  DOWNLOAD_WORD_GROUPED_PLAN_TEXT_03:
    "En un tono aún más claro representa a las asignaturas donde han aprobado entre un 49% y 25% de los estudiantes.",
  DOWNLOAD_WORD_GROUPED_PLAN_TEXT_04:
    "El tono de morado más claro de todos indica que la asignatura ha sido aprobada por menos del 25% de los estudiantes (pero al menos uno) han aprobado.",
  DOWNLOAD_WORD_GROUPED_PLAN_TEXT_05:
    "Finalmente, en color blanco están aquellas asignaturas en que ningún estudiante ha aprobado la asignatura.",
  GROPUED_COURSE_BOX_COLORS: [
    {
      val: 0,
      color: "#f2f0f7",
    },
    {
      val: 0.25,
      color: "#cbc9e2",
    },
    {
      val: 0.5,
      color: "#9e9ac8",
    },
    {
      val: 0.75,
      color: "#756bb1",
    },
    {
      val: 1,
      color: "#54278f",
    },
  ],
  PROGRESS_STUDENT_INFORMATION_BACKGROUND_COLOR: "rgb(252,249,165)",
  PROGRESS_STUDENT_INFORMATION_TEXT: "Avance en",
  ENTRY_YEAR_LABEL: "Ingreso",
  ERROR_PROGRAM_NOT_FOUND: "Programa especificado no pudo ser encontrado.",
  ERROR_PROGRAM_UNAUTHORIZED_MESSAGE:
    "No está autorizado para ver el programa especificado",
  ERROR_STUDENT_ACCOUNT_NO_DATA_MESSAGE:
    "Datos de estudiante no pudieron ser encontrados, favor de contactar a soporte.",
  ERROR_STUDENT_NOT_FOUND_MESSAGE:
    "Estudiante especificado no pudo ser encontrado en el programa especificado.",
  EXPLICIT_SEMESTER_COURSE_BOX_COLOR: "#ECC94B",
  FAIL_RATE_COLOR_SCALE_NEGATIVE_MAX_COLOR: "rgb(255,0,0)",
  FAIL_RATE_COLOR_SCALE_NEGATIVE_MIN_COLOR: "rgb(245,132,66)",
  FAIL_RATE_COLOR_SCALE_POSITIVE_MAX_COLOR: "#5bff3b",
  FAIL_RATE_COLOR_SCALE_POSITIVE_MIN_COLOR: "#b0ffa1",
  FEEDBACK_ENABLED: false,
  FEEDBACK_OPEN_TEXT_REQUIRED_ERROR_MESSAGE: "Ingrese su opinión",
  FEEDBACK_SINGLE_ANSWER_REQUIRED_ERROR_MESSAGE: "Eliga una opción",
  FEEDBACK_MULTIPLE_ANSWER_REQUIRED_ERROR_MESSAGE:
    "Debe especificar al menos 1 opción",
  FEEDBACK_SUBMIT_BUTTON_LABEL_TEXT: "Enviar Feedback",
  FLOW_CIRCLE_COLOR: "rgb(245,101,101)",
  FLOW_CIRCLE_LABEL: "Fluj",
  FLOW_COURSE_BOX_COLOR: "#F56565",
  FOREPLAN_COURSE_FUTURE_PLANIFICATION_FULFILLED_BORDER_COLOR: "#3182CE",
  FOREPLAN_MODE_SWITCH_ACTIVE_BACKGROUND_COLOR: "blue.500",
  FOREPLAN_MODE_SWITCH_ACTIVE_TEXT_COLOR: "white",
  FOREPLAN_MODE_SWITCH_FONT_FAMILY: "Lato",
  FOREPLAN_MODE_SWITCH_FONT_SIZE: "1.2em",
  FOREPLAN_MODE_SWITCH_HEIGHT: "3em",
  FOREPLAN_MODE_SWITCH_INACTIVE_BACKGROUND_COLOR: "gray.500",
  FOREPLAN_MODE_SWITCH_INACTIVE_TEXT_COLOR: "white",
  FOREPLAN_MODE_SWITCH_LABEL: "Plan Próximo Semestre",
  FOREPLAN_STATE_PREDICTION_PENDING_COLOR: "black",
  FOREPLAN_STATE_PREDICTION_APPROVED_COLOR: "green",
  FOREPLAN_STATE_PREDICTION_FAILED_COLOR: "red",
  FOREPLAN_STATE_PREDICTION_LABEL_PRE: "creo que",
  FOREPLAN_STATE_PREDICTION_APPROVED_SYMBOL: "A",
  FOREPLAN_STATE_PREDICTION_APPROVED_LABEL: "aprobaré",
  FOREPLAN_STATE_PREDICTION_FAILED_SYMBOL: "R",
  FOREPLAN_STATE_PREDICTION_FAILED_LABEL: "reprobaré",
  FOREPLAN_STATE_PREDICTION_UNKNOWN_SYMBOL: "?",
  FOREPLAN_STATE_PREDICTION_UNKNOWN_LABEL: "no lo sé",
  FOREPLAN_SUMMARY_ADVICE_FAIL_RATES_COLORS: {
    high: "#ffab91",
    mid: "#fed976",
    low: "#a1d99b",
  },
  FOREPLAN_SUMMARY_ADVICE_PARAGRAPH_FONT_SIZE: "0.9em",
  FOREPLAN_SUMMARY_ADVICE_TITLE_FONT_SIZE: "1.1em",
  FOREPLAN_SUMMARY_BACKGROUND_COLOR: "#333333",
  FOREPLAN_SUMMARY_BADGE_BACKGROUND_COLOR: "#EEEEEE",
  FOREPLAN_SUMMARY_BADGE_BORDER_RADIUS: "7px",
  FOREPLAN_SUMMARY_BADGE_COURSE_CREDITS_WIDTH: [
    {
      min: 0,
      max: 0,
      width: "8.2em",
    },
    {
      min: 1,
      max: 2,
      width: "8.9em",
    },
    {
      min: 3,
      max: 4,
      width: "9.4em",
    },
    {
      min: 5,
      max: 6,
      width: "9.8em",
    },
    {
      min: 7,
      max: 12,
      width: "10.5em",
    },
    {
      min: 13,
      max: 999,
      width: "11em",
    },
  ],
  FOREPLAN_SUMMARY_BADGE_COURSE_NAME_FONT_SIZE: "0.8em",
  FOREPLAN_SUMMARY_BADGE_EXPANDED_CREDITS_FONT_SIZE: "0.7em",
  FOREPLAN_SUMMARY_BADGE_FONT_COLOR: "black",
  FOREPLAN_SUMMARY_BADGE_FONT_SIZE: "0.9em",
  FOREPLAN_SUMMARY_BADGE_MARGIN: "3px",
  FOREPLAN_SUMMARY_BADGE_PADDING: "5px",
  FOREPLAN_SUMMARY_BORDER_RADIUS: "10px",
  FOREPLAN_SUMMARY_CONTENT_EXPANDED_PADDING: "2px",
  FOREPLAN_SUMMARY_FONT_COLOR: "white",
  FOREPLAN_SUMMARY_HEIGHT: 350,
  FOREPLAN_SUMMARY_LIST_BACKGROUND_COLOR: "#EEEEEE",
  FOREPLAN_SUMMARY_LIST_BORDER_RADIUS: "10px",
  FOREPLAN_SUMMARY_LIST_CODE_TEXT_PADDING: 1,
  FOREPLAN_SUMMARY_LIST_CODE_WIDTH: "7em",
  FOREPLAN_SUMMARY_LIST_NAME_TRUNCATE_LENGTH: 30,
  FOREPLAN_SUMMARY_LIST_NAME_WIDTH: "20em",
  FOREPLAN_SUMMARY_LIST_REMOVE_COURSE_ICON_SIZE: "20px",
  FOREPLAN_SUMMARY_LIST_ROW_MARGIN: 1,
  FOREPLAN_SUMMARY_LIST_ROW_PADDING: 1,
  FOREPLAN_SUMMARY_LIST_TEXT_COLOR: "black",
  FOREPLAN_SUMMARY_MOBILE_BREAKPOINT_HEIGHT: 1080,
  FOREPLAN_SUMMARY_MOBILE_BREAKPOINT_WIDTH: 1920,
  FOREPLAN_SUMMARY_TAB_COLOR: "#888",
  FOREPLAN_SUMMARY_TAB_ICON_SIZE: "1.3em",
  FOREPLAN_SUMMARY_TAB_NUMBER_FONT_SIZE: {
    oneDigit: "1.5em",
    twoDigits: "1.2em",
  },
  FOREPLAN_SUMMARY_TAB_WIDTH: "2em",
  FOREPLAN_SUMMARY_TITLE_FONT_SIZE: "1.1em",
  FOREPLAN_SUMMARY_TITLE_LABEL: "Plan semestre 1 2020",
  FOREPLAN_SUMMARY_TITLE_MARGIN_BOTTOM: "5px",
  FOREPLAN_SUMMARY_TOTAL_CREDITS_ADVICE_HELP_BODY_PADDING: "3px",
  FOREPLAN_SUMMARY_TOTAL_CREDITS_ADVICE_HELP_LABEL_FONT_COLOR: "black",
  FOREPLAN_SUMMARY_TOTAL_CREDITS_ADVICE_HELP_LABEL_BACKGROUND_COLOR: "white",
  FOREPLAN_SUMMARY_TOTAL_CREDITS_ADVICE_HELP_LABEL:
    "Los créditos son un estimado de la carga que significan los cursos a tomar",
  FOREPLAN_SUMMARY_TOTAL_CREDITS_ADVICE_HELP_WARNING_LABEL_FONT_COLOR: "white",
  FOREPLAN_SUMMARY_TOTAL_CREDITS_ADVICE_HELP_WARNING_LABEL_BACKGROUND_COLOR:
    "red.500",
  FOREPLAN_SUMMARY_TOTAL_CREDITS_ADVICE_HELP_WARNING_LABEL:
    "¡Cuidado! Estás tomando más créditos de los permitidos de forma regular, necesitarás elevar una solicitud para tomar esta carga",
  FOREPLAN_SUMMARY_TOTAL_CREDITS_LABEL: "Créditos totales",
  FOREPLAN_SUMMARY_TOTAL_CREDITS_LABEL_FONT_SIZE: "1.2em",
  FOREPLAN_SUMMARY_TOTAL_CREDITS_LABEL_COLOR: "black",
  FOREPLAN_SUMMARY_TOTAL_CREDITS_NUMBER_NORMAL_COLOR: "white !important",
  FOREPLAN_SUMMARY_TOTAL_CREDITS_NUMBER_WARNING_COLOR: "#d64843 !important",
  FOREPLAN_SUMMARY_TOTAL_CREDITS_NUMBER_NORMAL_FONT_SIZE: "1.2em",
  FOREPLAN_SUMMARY_TOTAL_CREDITS_NUMBER_WARNING_FONT_SIZE: "1.5em",
  FOREPLAN_SUMMARY_TOTAL_CREDITS_NO_WARNING_LIMIT: 30,
  FOREPLAN_SUMMARY_TOTAL_CREDITS_HELP_ICON_SIZE: "1.5em",
  FOREPLAN_SUMMARY_WAFFLE_COLORS_FAIL_RATE: {
    high: "#ffab91",
    mid: "#fed976",
    low: "#a1d99b",
  },
  FOREPLAN_SUMMARY_WAFFLE_HIGHLIGHT_BORDER: "1px solid white",
  FOREPLAN_SUMMARY_WAFFLE_HIGHLIGHT_BORDER_WIDTH: 1,
  FOREPLAN_SUMMARY_WAFFLE_HIGHLIGHT_BY_PERFORMANCE_LABEL: "rendimiento similar",
  FOREPLAN_SUMMARY_WAFFLE_HIGHLIGHT_BY_LOAD_LABEL: "carga similar",
  FOREPLAN_SUMMARY_WAFFLE_HIGHLIGHT_LABEL_COLOR: "white",
  FOREPLAN_SUMMARY_WAFFLE_LABEL_COLOR: "white",
  FOREPLAN_SUMMARY_WAFFLE_MARGIN_TOP: "7px",
  FOREPLAN_SUMMARY_WAFFLE_PADDING: "5px",
  FOREPLAN_SUMMARY_WAFFLE_RECT_SEPARATION: 1.2,
  FOREPLAN_SUMMARY_WAFFLE_SIZE: 94,
  FOREPLAN_SUMMARY_WAFFLE_SQUARE_SIZE: 8,
  FOREPLAN_SUMMARY_WAFFLE_LABEL_BY_LOAD: "créd",
  FOREPLAN_SUMMARY_WAFFLE_LABEL_UPPER_BOUNDARY: 50,
  FOREPLAN_SUMMARY_WAFFLE_LABEL_UPPER_BOUNDARY_TEXT: "+",
  FOREPLAN_WARNING_INDIRECT_TAKE_ICON_SIZE: "50px",
  FOREPLAN_WARNING_INDIRECT_TAKE_BODY:
    "Para poder tomar <Code /> - <Name /> necesitarás mandar una solicitud.",
  FOREPLAN_WARNING_INDIRECT_TAKE_BODY_FONT_SIZE: "1.5em",
  FOREPLAN_WARNING_INDIRECT_TAKE_TITLE:
    "No puedes tomar esta asignatura de forma inmediata!",
  FOREPLAN_WARNING_INDIRECT_TAKE_TITLE_FONT_SIZE: "2em",
  FOREPLAN_WARNING_INDIRECT_TAKE_CLOSE_BUTTON_LABEL: "De acuerdo",
  GRADES_LABEL: "Calificaciones",
  GRADES_SCALES: "Escala de notas",
  HELP_ENABLED: false,
  HISTOGRAM_BAR_ACTIVE: "rgb(122,122,122)",
  HISTOGRAM_BAR_INACTIVE: "rgb(191,191,191)",
  GROUPED_HISTOGRAM_BAR: "rgb(173,66,244)",
  HISTORIC_GRADES: "Calificaciones históricas",
  GROUPED_GRADES: "Calificaciones grupo",
  INACTIVE_COURSE_BOX_COLOR: "#A0AEC0",
  LOGIN_BUTTON: "Ingresar",
  LOGIN_EMAIL_LABEL: "Correo Electrónico",
  LOGIN_EMAIL_PLACEHOLDER: "email@uach.cl",
  LOGIN_ERROR_TITLE: "Error!",
  LOGIN_LOCKED_USER_MESSAGE:
    "Usuario bloqueado. Por favor revisar correo para recuperar su cuenta.",
  LOGIN_PASSWORD_LABEL: "Contraseña",
  LOGIN_PASSWORD_PLACEHOLDER: "contraseña",
  LOGIN_PUT_VALID_EMAIL: "Ingrese un Email Válido",
  LOGIN_PUT_VALID_PASSWORD_LENGTH: "Ingrese una contraseña válida",
  LOGIN_REMEMBER_SESSION: "Mantenerse conectado",
  LOGIN_WRONG_INFO_MESSAGE:
    "Información ingresada erronea. Verificar datos o su cuenta puede ser bloqueda por seguridad.",
  LOGOUT_BUTTON_LABEL: "Salir",
  LOGOUT_CONFIRMATION_LABEL: "¿Está seguro que desea cerrar sesión?",
  MAX_FAIL_SCALE_COLOR: "#ff8282",
  MAX_GRADE: 7,
  MAX_PASS_SCALE_COLOR: "#5bff3b",
  MIN_FAIL_SCALE_COLOR: "#ff4040",
  MIN_GRADE: 1,
  MIN_GRADE_EXTERNAL_EVALUATION: 0,
  MAX_GRADE_EXTERNAL_EVALUATION: 100,
  LIST_GRADES: ["A", "B", "C", "D"],
  MENTION: "Mención: ",
  MIN_PASS_SCALE_COLOR: "#b0ffa1",
  NO_CURRICULUMS_LABEL: "Sin planes",
  NO_HISTORIC_DATA: "No hay datos a mostrar",
  PARALLEL_GROUP_BACKGROUND_COLOR: "#ddd",
  PARALLEL_GROUP_LABEL: "GP",
  PARALLEL_GROUP_LABEL_COLOR: "black",
  PASS_GRADE: 4,
  PLACEHOLDER_SEARCH_STUDENT: "ID del estudiante",
  GRADE_STUDENT_LABEL: "Logrado",
  PROGRAM_GRADE_COLOR: "rgb(102,102,102)",
  PROGRAM_GRADE_LABEL: "PGA de carrera",
  CURRICULUM_GRADE_LABEL: "PGA de plan",
  FILTERED_GRADE_LABEL: "PGA filtrada",
  PROGRAM_NOT_SPECIFIED_PLACEHOLDER: "Programa no especificado",
  PROGRESS_LABEL: "Progreso",
  REQUISITE_COURSE_BOX_COLOR: "#4299E1",
  REQ_CIRCLE_COLOR: "rgb(66,153,225)",
  REQ_CIRCLE_LABEL: "Req",
  RISK_HIGH_COLOR: "rgb(255,0,0)",
  RISK_HIGH_THRESHOLD: 80,
  RISK_LABEL: "Percentil riesgo",
  RISK_LOW_COLOR: "rgb(128,255,0)",
  RISK_MEDIUM_COLOR: "rgb(252,186,3)",
  RISK_MEDIUM_THRESHOLD: 50,
  SEARCH_BAR_BACKGROUND_COLOR: "rgb(52,58,64)",
  SEARCH_BUTTON_LABEL: "Buscar",
  SEMESTER_HEADER_FONT_SIZE: "1.5em",
  SEMESTER_HEADER_TEXT_COLOR: "rgb(70,130,180)",
  SEMESTRAL_GRADE_COLOR: "rgb(70,130,180)",
  SEMESTRAL_GRADE_LABEL: "PSP",
  STATE_CANCELED_LABEL_MINI: "An",
  STATE_COLOR_FAIL_FALLBACK: "rgb(214,96,77)",
  STATE_COLOR_PASS_FALLBACK: "rgb(102,180,62)",
  STATE_COURSE_CANCELED_COLOR: "white",
  STATE_COURSE_CIRCLE_STROKE: "white",
  STATE_COURSE_CURRENT_COLOR: "blue.500",
  STATE_COURSE_PENDING_COLOR: "blue.300",
  STATE_COURSE_DEFAULT_DARK_COLOR: "#181A1B",
  STATE_CURRENT_LABEL_MINI: "Reg",
  STATE_FAILED_LABEL_MINI: "Rep",
  STATE_PASSED_LABEL_MINI: "Apr",
  STATE_PENDING_LABEL_MINI: "Pen",
  STUDENT_PROGRESS: "Progreso del estudiante",
  STUDENT_LABEL: "Estudiante",
  STUDENT_LIST_TITLE: "Lista de estudiantes",
  STUDENT_REPORT: "Informe de Estudiantes",
  TAKEN_SEMESTER_BOX_ACTIVE: "yellow.400",
  TAKEN_SEMESTER_BOX_BACKGROUND_COLOR: "rgb(245,245,245)",
  TAKEN_SEMESTER_BOX_BORDER: "3px solid",
  TAKEN_SEMESTER_BOX_BORDER_RADIUS: "8px",
  TAKEN_SEMESTER_BOX_FONT_SIZE: "1.2em",
  TAKEN_SEMESTER_BOX_HEIGHT: "3em",
  TAKEN_SEMESTER_BOX_INACTIVE: "grey",
  TAKEN_SEMESTER_BOX_MARGIN_SIDES: 3,
  TAKEN_SEMESTER_BOX_PADDING: "7.5px",
  TAKEN_SEMESTER_BOX_TEXT_COLOR: "black",
  TAKEN_SEMESTER_BOX_TRANSITION: "all 0.4s ease-in-out",
  TIMELINE_AXIS_COLOR: "black",
  TIMELINE_AXIS_TEXT_COLOR: "black",
  TIMELINE_EXPLICIT_CIRCLE_COLOR: "rgb(236,201,75)",
  TIMELINE_PASS_LINE_COLOR: "black",
  TIMELINE_TOOLTIP_TEXT_COLOR: "rgb(255,255,255)",
  UNLOCK_ACTIVE_ACCOUNT_LABEL: "Activar cuenta",
  UNLOCK_ERROR_TITLE: "Error!",
  UNLOCK_LENGTH_VALIDATION:
    "El largo de la contraseña tiene que ser de al menos 8 caracteres y máximo de 100 caracteres.",
  UNLOCK_LOWERCASE_VALIDATION:
    "La contraseña debe contener al menos una letra minúscula.",
  UNLOCK_NEW_PASSWORD_LABEL: "Nueva contraseña",
  UNLOCK_NEW_PASSWORD_PLACEHOLDER: "contraseña",
  UNLOCK_NEW_PASSWORD_REPEAT_LABEL: "Repita su contraseña",
  UNLOCK_NUMBER_VALIDATION: "La contraseña debe contener al menos un número.",
  UNLOCK_REPEAT_VALIDATION: "Debe repetir su contraseña correctamente.",
  UNLOCK_SPECIAL_SYMBOL_VALIDATION:
    "La contraseña debe contener al menos un caracter especial (~¡!$&+,:;=¿?@#|'<>.^*(){}\"%-_).",
  UNLOCK_UPPERCASE_VALIDATION:
    "La contraseña debe contener al menos una letra mayúscula.",
  UNLOCK_USER_OLD_PASSWORD_MESSAGE:
    "No puede ingresar una contraseña usada anteriormente.",
  UNLOCK_WRONG_INFO_MESSAGE:
    "Usuario ingresado no está bloqueado o el código ingresado es erróneo.",
  HELP_POPOVER_HOVER_TEXT: "Ayuda",
  HELP_MODAL_HEADER_TEXT: "Ayuda",
  VERSION_CONFIG: "1",
  MESSAGE_HEADER: "Estimado/a Director/a",
  MESSAGE_CLOSING:
    "Si tiene algún problema o alguna pregunta, puede contactarnos al correo: ",
  MESSAGE_FAREWELL: "Saludos cordiales, Equipo TrAC-FID",
  MESSAGE_FOOTER:
    " Por favor no responda este email. Este correo fue generado de manera automática por TrAC-FID y enviado a : ",
  MESSAGE_SUBJECT: "Novedades en TrAC-FID",
  DEFAULT_MESSAGE: "Se ha actualizado la base de datos de TrAC-FID",
  NO_INFORMATION_TO_DEPLOY: "No hay información para mostrar",
  RISK_ALL: "Todos",
  RISK_STUDENT_PENDING_OF_GRADUATION: "Pendientes de Titulación ",
  RISK_HIGH_DROP_RATE: "Cursos con alto tasa de anulacion",
  RISK_LOW_PROGRESSING_RATE: "Avance menor al umbral (50%)",
  MESSAGE_RISK_HEADER: "Situaciones de riesgo",
  MESSAGE_RISK_BODY: "Se han encontrado las siguientes situaciones de riesgo: ",
  MESSAGE_RISK_GIF: "Cómo visualizar situaciones de riesgo en TrAC-FID : ",
  MESSAGE_RISK_FOOTER: "Para mayor información visite : ",
  RISK_THIRD_ATTEMPT: "Asignaturas por tercera vez",
  RISK_LOW_PASSING_RATE_COURSES: "Cursos con bajo nivel de aprobación",
  GROUPED_DATA: "Datos agrupados",
  EMPLOYABILITY_DATA: "Datos empleabilidad",
  ACADEMIC_DATA: "Datos académicos",
  EXTERNAL_DATA: "Datos externos",
  LAST_UPDATE_DATA: "Fecha de última carga de datos",
  NOTIFICATIONS_EMAIL_ADDRESS: "soportelala@inf.uach.cl",
  SHOW_PARAMETER: true,
  COURSE_LABEL: "Asignatura",
  YEAR_LABEL: "Año",
  TERM_LABEL: "Semestre",
  RATE_LABEL: "Tasa",
};

export const baseConfigAdmin: typeof baseConfig &
  Record<string, any> = baseConfig;
